version: '3'
services:
  xo_server:
    restart: unless-stopped
    build:
      context: ./build
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis_db
    environment:
      - DEBUG=xo:main
      - XOA_PLAN=5
      - TZ="America/Toronto"
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - xo-data:/var/lib/xo-server
    logging: &default_logging
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      - frontend
      - backend

  redis_db:
    restart: unless-stopped
    image: docker.io/library/redis:7-bookworm
    command: redis-server --appendonly yes
    expose:
      - 6379
    volumes:
      - redis-data:/var/lib/redis
    logging:
      <<: *default_logging
    networks:
      - backend


## Volumes
volumes:
  xo-data:
  redis-data:


## Networks
networks:
  frontend:
  backend: